app/Project_6-8/Project_6-8/Models/Model1.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_6_8.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class XAY_DUNG1Entities2 : DbContext
    {
        public XAY_DUNG1Entities2()
            : base("name=XAY_DUNG1Entities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Project> Projects { get; set; }
    }
}

app/Project_6-8/Project_6-8/Models/Model1.Designer.cs
// T4 code generation is enabled for model 'C:\Users\gbuid\OneDrive\Desktop\XAY_DUNG\Project_6-8\Project_6-8\Models\Model1.edmx'. 
// To enable legacy code generation, change the value of the 'Code Generation Strategy' designer
// property to 'Legacy ObjectContext'. This property is available in the Properties Window when the model
// is open in the designer.

// If no context and entity classes have been generated, it may be because you created an empty model but
// have not yet chosen which version of Entity Framework to use. To generate a context class and entity
// classes for your model, open the model in the designer, right-click on the designer surface, and
// select 'Update Model from Database...', 'Generate Database from Model...', or 'Add Code Generation
// Item...'.

app/Project_6-8/Project_6-8/Models/Model1.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

app/Project_6-8/Project_6-8/Models/Project.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_6_8.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Project
    {
        public int ID_Project { get; set; }
        [Required(ErrorMessage = "Tên không được để trống.")]
        public string Name_Project { get; set; }
        [Required(ErrorMessage = "Nơi thi công không được để trống.")]
        public string Detail_Project { get; set; }
        [Required(ErrorMessage = "Link hình ảnh không được để trống.")]
        public string Image_Project { get; set; }
        public string Type_Project { get; set; }
    }
}

app/Project_6-8/Project_6-8/Controllers/HomeController.cs
using Project_6_8.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Project_6_8.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {

            return View();
        }
        public ActionResult About()
        {

            return View();
        }

        public ActionResult Contact()
        {

            return View();
        }
        [Route("Home/ProjectDetail/{id}")]
        public ActionResult ProjectDetail(int? id)
        {
            if (id is null)
            {
                throw new ArgumentNullException(nameof(id));
            }
            else
            {
                var select = GetProjectbyID(id);
                return View(select);
            }
        }

        public ActionResult Project()
        {
            using (var db = new XAY_DUNG1Entities2())
            {
                var select = db.Projects.ToList();
                return View(select);
            }
        }

        private List<Project> GetProjectbyID(int? id)
        {
            using (var db = new XAY_DUNG1Entities2())
            {
                var select = (from s in db.Projects where s.ID_Project == id select s).ToList();
                return select;
            }
        }
    }
}

app/Project_6-8/Project_6-8/Controllers/ProjectsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Project_6_8.Models;

namespace Project_6_8.Controllers
{
    public class ProjectsController : Controller
    {
        private XAY_DUNG1Entities2 db = new XAY_DUNG1Entities2();

        // GET: Projects
        public ActionResult Index()
        {
            return View(db.Projects.ToList());
        }

        // GET: Projects/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Project project = db.Projects.Find(id);
            if (project == null)
            {
                return HttpNotFound();
            }
            return View(project);
        }

        // GET: Projects/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Projects/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_Project,Name_Project,Detail_Project,Image_Project,Type_Project")] Project project)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    db.Projects.Add(project);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                catch (Exception e)
                {
                    Console.WriteLine(e);
                }
            }

            return View(project);
        }

        // GET: Projects/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Project project = db.Projects.Find(id);
            if (project == null)
            {
                return HttpNotFound();
            }
            return View(project);
        }

        // POST: Projects/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_Project,Name_Project,Detail_Project,Image_Project,Type_Project")] Project project)
        {
            if (ModelState.IsValid)
            {
                db.Entry(project).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(project);
        }

        // GET: Projects/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Project project = db.Projects.Find(id);
            if (project == null)
            {
                return HttpNotFound();
            }
            return View(project);
        }

        // POST: Projects/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Project project = db.Projects.Find(id);
            db.Projects.Remove(project);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

app/Project_6-8/Project_6-8/Views/Projects/Create.cshtml
@model Project_6_8.Models.Project

@{
    ViewBag.Title = "Create";
}

<nav class="gtco-nav" role="navigation">
    <div class="gtco-container">
        <div class="row">
            <div class="col-sm-2 col-xs-12">
                <div id="gtco-logo">@Html.ActionLink("Beryllium", "Index", "Home")</div>
            </div>
            <div class="col-xs-10 text-right menu-1" id="mydiv" runat="server">
                <ul>
                    <li class="active">
                        @Html.ActionLink("Trang chủ", "Index", "Home")
                    </li>
                    <li>
                        @Html.ActionLink("Liên hệ", "Contact", "Home")
                    </li>
                    <li>
                        @Html.ActionLink("Dự Án", "Index", "Projects")
                    </li>
                </ul>
            </div>
        </div>

    </div>
</nav>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="gtco-section">
        <div class="gtco-container">
            <div class="form-horizontal">
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    <label class="control-label col-md-2" style="font-size:20px;">Tên dự án</label>
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Name_Project, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name_Project, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-2" style="font-size:20px;">Nơi thi công</label>
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Detail_Project, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Detail_Project, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-2" style="font-size:20px;">Link hình ảnh</label>
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Image_Project, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Image_Project, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-2" style="font-size:20px;">Loại dự án</label>
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Type_Project, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Type_Project, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Create" class="btn btn-default" />
                    </div>
                </div>
            </div>
            <div>
                @Html.ActionLink("Back to List", "Index")
            </div>
        </div>
    </div>
}

app/Project_6-8/Project_6-8/Views/Projects/Delete.cshtml
@model Project_6_8.Models.Project

@{
    ViewBag.Title = "Delete";
}
<nav class="gtco-nav" role="navigation">
    <div class="gtco-container">
        <div class="row">
            <div class="col-sm-2 col-xs-12">
                <div id="gtco-logo">@Html.ActionLink("Beryllium", "Index", "Home")</div>
            </div>
            <div class="col-xs-10 text-right menu-1" id="mydiv" runat="server">
                <ul>
                    <li class="active">
                        @Html.ActionLink("Trang chủ", "Index", "Home")
                    </li>
                    <li>
                        @Html.ActionLink("Liên hệ", "Contact", "Home")
                    </li>
                    <li>
                        @Html.ActionLink("Dự Án", "Index", "Projects")
                    </li>
                </ul>
            </div>
        </div>

    </div>
</nav>
<div class="gtco-section">
    <div class="gtco-container">
        <h4 class="text-warning" style="font-size:24px">Are you sure you want to delete this?</h4>
        <div>
            <hr />
            <dl class="dl-horizontal">
                <dt>
                    <label class="control-label col-md-2" style="font-size:20px;">Tên dự án</label>
                </dt>

                <dd style="font-size:20px">
                    @Html.DisplayFor(model => model.Name_Project)
                </dd>

                <dt>
                    <label class="control-label col-md-2" style="font-size:20px;">Nơi thi công</label>
                </dt>

                <dd style="font-size:20px">
                    @Html.DisplayFor(model => model.Detail_Project)
                </dd>

                <dt>
                    <label class="control-label col-md-2" style="font-size:20px;">Link hình ảnh</label>
                </dt>

                <dd style="font-size:20px">
                    @Html.DisplayFor(model => model.Image_Project)
                </dd>

                <dt>
                    <label class="control-label col-md-2" style="font-size:20px;">Loại dự án</label>
                </dt>

                <dd style="font-size:20px">
                    @Html.DisplayFor(model => model.Type_Project)
                </dd>

            </dl>

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-actions no-color">
                    <input type="submit" value="Delete" class="btn btn-default" />
                    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn_primary" })
                </div>
            }
        </div>
    </div>
</div>

app/Project_6-8/Project_6-8/Views/Projects/Details.cshtml
@model Project_6_8.Models.Project

@{
    ViewBag.Title = "Details";
}
<nav class="gtco-nav" role="navigation">
    <div class="gtco-container">
        <div class="row">
            <div class="col-sm-2 col-xs-12">
                <div id="gtco-logo">@Html.ActionLink("Beryllium", "Index", "Home")</div>
            </div>
            <div class="col-xs-10 text-right menu-1" id="mydiv" runat="server">
                <ul>
                    <li>
                        @Html.ActionLink("Trang chủ", "Index", "Home")
                    </li>
                    <li>
                        @Html.ActionLink("Liên hệ", "Contact", "Home")
                    </li>
                    <li class="active">
                        @Html.ActionLink("Dự Án", "Project", "Home")
                    </li>
                </ul>
            </div>
        </div>

    </div>
</nav>
<section class="htc__project__details__page ptb--150 bg__white">
    <div class="container">
        <div class="row">
                <div class="col-md-8 col-lg-8 col-sm-12 col-xs-12">
                    <div class="htc__single__service">
                        <div class="htc__single__service__tab">
                            <div class="ht-portfolio-pic-show">
                                <div class="ht-portfolio-full-image tab-content">
                                    <div role="tabpanel" class="tab-pane fade in active" id="img-tab-1">
                                        <img src="@Model.Image_Project" alt="full-image" style="">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                    <div class="single__project__rightsidebar">
                        <!-- Start Single Item -->
                        <div class="pro__dtl__inner bg__gray">
                            <h2>PROJECT DETAILS</h2>
                            <div class="pro__dtl__content">
                                <ul class="pro__dtl__list font__bold">
                                    <li>TÊN :</li>
                                    <li>NƠI THI CÔNG :</li>
                                    <li>DẠNG CÔNG TRÌNH :</li>
                                </ul>
                                <ul class="pro__dtl__list">
                                    <li> @Html.DisplayFor(model => model.Name_Project)</li>
                                    <li> @Html.DisplayFor(model => model.Detail_Project)</li>
                                    @if (Model.Type_Project == null)
                                    {
                                        <li>CONSTRUCTION</li>
                                    }
                                    else
                                    {
                                        <li> @Html.DisplayFor(model => model.Type_Project)</li>
                                    }

                                </ul>
                            </div>
                        </div>
                        <p>
                            @Html.ActionLink("Edit", "Edit", new { id = Model.ID_Project }, new { @class = "btn btn_primary" }) 
                            @Html.ActionLink("Delete", "Delete", new { id = Model.ID_Project }, new { @class = "btn btn_primary" }) 
                            @Html.ActionLink("Back to List", "Index", null,new { @class = "btn btn_primary" })
                        </p>
                        <!-- End Single Item -->
                    </div>
                </div>
        </div>
    </div>
</section>

app/Project_6-8/Project_6-8/Views/Projects/Edit.cshtml
@model Project_6_8.Models.Project

@{
    ViewBag.Title = "Edit";
}
<nav class="gtco-nav" role="navigation">
    <div class="gtco-container">
        <div class="row">
            <div class="col-sm-2 col-xs-12">
                <div id="gtco-logo">@Html.ActionLink("Beryllium", "Index", "Home")</div>
            </div>
            <div class="col-xs-10 text-right menu-1" id="mydiv" runat="server">
                <ul>
                    <li class="active">
                        @Html.ActionLink("Trang chủ", "Index", "Home")
                    </li>
                    <li>
                        @Html.ActionLink("Giới thiệu", "About", "Home")
                    </li>
                    <li>
                        @Html.ActionLink("Dự Án", "Index", "Projects")
                    </li>
                </ul>
            </div>
        </div>

    </div>
</nav>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="gtco-section">
        <div class="gtco-container">
            <div class="form-horizontal">
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.ID_Project)

                <div class="form-group">
                    <label class="control-label col-md-2" style="font-size:20px;">Tên dự án</label>
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Name_Project, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name_Project, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-2" style="font-size:20px;">Nơi thi công</label>
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Detail_Project, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Detail_Project, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-2" style="font-size:20px;">Link hình ảnh</label>
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Image_Project, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Image_Project, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-2" style="font-size:20px;">Loại dự án</label>
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Type_Project, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Type_Project, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Save" class="btn btn-default" />
                    </div>
                </div>
            </div>
            <div>
                @Html.ActionLink("Back to List", "Index")
            </div>
        </div>
    </div>
}

app/Project_6-8/Project_6-8/Views/Projects/Index.cshtml
@model IEnumerable<Project_6_8.Models.Project>

@{
    ViewBag.Title = "Index";
}
<nav class="gtco-nav" role="navigation">
    <div class="gtco-container">
        <div class="row">
            <div class="col-sm-2 col-xs-12">
                <div id="gtco-logo">@Html.ActionLink("Beryllium", "Index", "Home")</div>
            </div>
            <div class="col-xs-10 text-right menu-1" id="mydiv" runat="server">
                <ul>
                    <li>
                        @Html.ActionLink("Trang chủ", "Index", "Home")
                    </li>
                    <li>
                        @Html.ActionLink("Liên hệ", "Contact", "Home")
                    </li>
                    <li class="active">
                        @Html.ActionLink("Dự Án", "Project", "Home")
                    </li>
                </ul>
            </div>
        </div>

    </div>
</nav>

<div class="wrapper" style="text-align:center;margin:auto">
    @Html.ActionLink("Create New", "Create", null, new { @class = "btn btn_primary" })
</div>
<section class="htc__latest__project__area ptb--150 bg__white">
    <div class="container">
        <div class="row">
            <div class="htc__latest__project__wrap clearfix">
                <!-- Start Single Project -->
                @{foreach (var item in Model)
                    {
                        <div class="col-md-4 col-lg-4 col-sm-6 col-xs-12">
                            <div class="project foo" data-dr-id="1" style="visibility: visible;  -webkit-transform: translateY(0) scale(1); opacity: 1;transform: translateY(0) scale(1); opacity: 1;-webkit-transition: -webkit-transform 0.8s cubic-bezier(0.6, 0.2, 0.1, 1) 0s, opacity 0.8s cubic-bezier(0.6, 0.2, 0.1, 1) 0s; transition: transform 0.8s cubic-bezier(0.6, 0.2, 0.1, 1) 0s, opacity 0.8s cubic-bezier(0.6, 0.2, 0.1, 1) 0s; ">
                                <div class="project__thumb">
                                    <a href="/Projects/Details/@item.ID_Project">
                                        <img src="@item.Image_Project" alt="project images">
                                    </a>
                                    <div class="project__hover__info">
                                        <div class="project__action">
                                            <h2><a href="/Projects/Details/@item.ID_Project">@item.Name_Project</a></h2>
                                            <h4>@item.Detail_Project</h4>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                }
                <!-- End Single Project -->
            </div>
        </div>
    </div>
</section>
    </table>

app/Project_6-8/Project_6-8/Views/Shared/_Layout.cshtml
<!DOCTYPE HTML>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Beryllium &mdash; Free Website Template, Free HTML5 Template by gettemplates.co</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Free HTML5 Website Template by gettemplates.co" />
    <meta name="keywords" content="free website templates, free html5, free template, free bootstrap, free website template, html5, css3, mobile first, responsive" />
    <meta name="author" content="gettemplates.co" />
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Facebook and Twitter integration -->
    <meta property="og:title" content="" />
    <meta property="og:image" content="" />
    <meta property="og:url" content="" />
    <meta property="og:site_name" content="" />
    <meta property="og:description" content="" />
    <meta name="twitter:title" content="" />
    <meta name="twitter:image" content="" />
    <meta name="twitter:url" content="" />
    <meta name="twitter:card" content="" />

    <link href="https://fonts.googleapis.com/css?family=Merriweather:300,400|Montserrat:400,700" rel="stylesheet">

    <!-- Animate.css -->
    <link href="~/Content/css/animate.css" rel="stylesheet" />
    <!-- Icomoon Icon Fonts-->
    <link rel="stylesheet" href="~/Content/css/icomoon.css">
    <!-- Themify Icons-->
    <link rel="stylesheet" href="~/Content/css/themify-icons.css">
    <!-- Bootstrap  -->
    <link rel="stylesheet" href="~/Content/css/bootstrap.css">
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <!-- Owl Carousel  -->
    <link href="~/Content/css/owl.theme.default.min.css" rel="stylesheet" />
    <link href="~/Content/css/owl.carousel.min.css" rel="stylesheet" />
    <!-- Theme style  -->
    <link href="~/Content/css/core.css" rel="stylesheet" />
    <link href="~/Content/css/custom.css" rel="stylesheet" />
    <link href="~/Content/css/shortcodes.css" rel="stylesheet" />
    <link href="~/Content/css/responsive.css" rel="stylesheet" />
    <link href="~/Content/css/style.css" rel="stylesheet">

    <!-- Modernizr JS -->
    <script src="~/Scripts/js/modernizr-2.6.2.min.js"></script>


    <script src="~/Scripts/modernizr-2.8.3.js"></script>
    <!-- FOR IE9 below -->
    <script src="js/respond.min.js"></script>

</head>
<body>

    <div id="page">

        @RenderBody()
        <!-- END  -->
        <div class="gtco-section gto-features">
            <div class="gtco-container">
                <div class="row">
                    <div class="col-md-4">
                        <div class="feature-left">
                            <i class="ti-zip icon"></i>
                            <div class="copy">
                                <h3>Architect</h3>
                                <p>Lorem ipsum dolor sit ameteista, consectetur adipiscing is not elitistaris.</p>
                                <p><a href="#" class="gtco-more">Learn more</a></p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="feature-left">
                            <i class="ti-hummer icon"></i>
                            <div class="copy">
                                <h3>Planning</h3>
                                <p>Lorem ipsum dolor sit ameteista, consectetur adipiscing is not elitistaris.</p>
                                <p><a href="#" class="gtco-more">Learn more</a></p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="feature-left">
                            <i class="ti-plug icon"></i>
                            <div class="copy">
                                <h3>Parks &amp; Events</h3>
                                <p>Lorem ipsum dolor sit ameteista, consectetur adipiscing is not elitistaris.</p>
                                <p><a href="#" class="gtco-more">Learn more</a></p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <footer id="gtco-footer" class="gtco-section" role="contentinfo">
            <div class="gtco-container">
                <div class="row row-pb-md">
                    <div class="col-md-4 gtco-widget gtco-footer-paragraph">
                        <h3>Beryllium</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus placerat enim et urna sagittis, rhoncus euismod.</p>
                    </div>
                    <div class="col-md-8 gtco-footer-subscribe">
                        <form class="form-inline">
                            <div class="form-group">
                                <ul>
                                    <li class="address">Số 1 Phố Xốm, Phú Lâm, Hà Đông, Hà Nội, Việt Nam</li>
                                    <li class="phone"><a href="tel://0374394005">0374 394 005</a></li>
                                    <li class="email"><a href="mailto:hieu187110@gmail.com">hieu187110@gmail.com</a></li>
                                    <li class="url"><a href="https://www.facebook.com/hieuiii">Nguyễn Hiếu</a></li>
                                </ul>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </footer>
        <!-- END footer -->

    </div>

    <div class="gototop js-top">
        <a href="#" class="js-gotop"><i class="icon-arrow-up"></i></a>
    </div>

    <!-- jQuery -->
    <script src="~/Scripts/js/jquery.min.js"></script>
    <!-- jQuery Easing -->
    <script src="~/Scripts/js/jquery.easing.1.3.js"></script>
    <!-- Bootstrap -->
    <script src="~/Scripts/js/bootstrap.min.js"></script>
    <!-- Waypoints -->
    <script src="~/Scripts/js/jquery.waypoints.min.js"></script>
    <!-- Carousel -->
    <script src="~/Scripts/js/owl.carousel.min.js"></script>

    <!-- Main -->
    <script src="~/Scripts/js/main.js"></script>
    <script src="~/Scripts/js/jquery-1.12.0.min.js"></script>
    <script src="~/Scripts/js/plugins.js"></script>
    <script src="~/Scripts/js/slick.min.js"></script>
    <script src="~/Scripts/js/waypoints.min.js"></script>
    <script src="~/Scripts/js/main2.js"></script>

</body>
</html>