routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/','ShopController@index')->name('shop.index');

Route::get('/lien-he', 'ShopController@contact')->name('shop.contact');
Route::post('/lien-he', 'ShopController@postContact')->name('shop.postContact');

Route::get('/index','ShopController@index')->name('shop.index');

Route::get('/Category/{type}','ShopController@Category')->name('shop.category');
Route::get('/chitietsanpham/{id}','ShopController@Chitietsanpham')->name('shop.chitietsanpham');
Route::get('/article','ShopController@Articles')->name('shop.article');
Route::get('/tim-kiem','ShopController@Seach')->name('shop.timkiem');
Route::get('/dang-ky','ShopController@Register')->name('shop.register');
Route::post('dang-ky','ShopController@postRegister')->name('shop.postRegister');
Route::get('/dang-nhap','ShopController@Login')->name('shop.Login');
Route::post('dang-nhap','ShopController@postLogin')->name('shop.postLogin');

Route::get('/admin/logout', 'ShopController@logout')->name('admin.logout');

// //trang danh sách giỏ hàng
Route::get('/danhsachgiohang','CartController@index')->name('cart.index');

//thêm sản phẩm vào giỏ hàng
Route::get('/giohang/{id}','CartController@addtoCart')->name('cart.addcart');

Route::get('Delete-cart/{id}','CartController@DeleteCart')->name('delete.cart');

Route::get('cap-nhap-so-luong-sp','CartController@updateCart')->name('update.cart');
Route::get('huy-don-hang','CartController@destroy')->name('destroy.cart');

Route::get('order-product','ShopController@OrderProduct')->name('order.product');







Route::get('/admin', 'AdminController@login')->name('admin.index');
Route::get('/admin/login', 'AdminController@login')->name('admin.login');
Route::post('/admin/login', 'AdminController@postLogin')->name('admin.postLogin');






Route::group(['prefix' => 'admin','as'=>'admin.'], function(){
    Route::post('/store','LoginController@store');
    Route::resource('photo', 'PhotoController');
    Route::resource('vendor', 'VendorController');
    Route::resource('category', 'CategoryController');
    Route::resource('user','UserController');
    Route::resource('banner','BannerController');
    Route::resource('product','ProductController');
    Route::resource('article','ArticlesController');
    Route::resource('setting', 'settingController');
    Route::resource('contact', 'ContactController');
});

app/Banner.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Banner extends Model
{
    public $timestamp = false;
    protected $fillable =[
        'title','slug','image','created_at'
    ];
}

app/Http/Controllers/BannerController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Banner;

use Illuminate\Support\Facades\DB;

class BannerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $banner = DB::table('banners')->select('*');
        $banner = $banner->get();
        $banner = Banner::latest()->paginate(5);
        return view('backend.banner.index',compact('banner'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view ('backend.banner.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'title' =>'required',
            'slug' =>'required',
            'created_at'=> 'required',
            'image' => 'required'
        ]);

        $title = $request->input('title');
        $slug = $request->input('slug');
        
        $is_active = 0; // default
        if ($request->has('is_active')) {
            $is_active = (int) $request->input('is_active');
        }
       

        $path_avatar = '';
        if ($request->hasFile('image')) {
            // get file
            $file = $request->file('image');
            // get ten
            $filename = $file->getClientOriginalName(); // lấy tên gốc của ảnh
            // duong dan upload
            $path_upload = 'upload/banner/';
            // upload file
            $file->move($path_upload, $filename);
            $path_avatar = $path_upload.$filename;

            $Ban = new Banner();
            $Ban ->title = $title;
            $Ban->slug=$slug;
            $Ban->image = $path_avatar;

            
            //lưu
            $Ban->save();
            // chuyển hướng điều trang
            return redirect()->route('admin.banner.index');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $banner = Banner::find($id);
        return view('backend.banner.edit', compact('banner'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $name = $request->input('title');
        $slug = $request->input('slug');

        $is_active = 0; // default
        if ($request->has('is_active')) {
            $is_active = (int) $request->input('is_active');
        }

        $path_avatar = '';
        if ($request->hasFile('image')) {
            // get file
            $file = $request->file('image');
            // get ten
            $filename = $file->getClientOriginalName(); // lấy tên gốc của ảnh
            // duong dan upload
            $path_upload = 'upload/banner/';
            // upload file
            $file->move($path_upload, $filename);
            $path_avatar = $path_upload.$filename;

            $Ban = Banner::find($id);
            $Ban ->title = $name;
            $Ban->slug  = $slug;
            $Ban->image = $path_avatar;
            //lưu
            $Ban->save();
            // chuyển hướng điều trang
            return redirect()->route('admin.banner.index');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $isDelete = Banner::destroy($id);

        if ($isDelete) { // xóa thành công
            return response()->json(['isSuccess' => 1,'message'=>'Thành công']);
        } else {
            return response()->json(['isSuccess' => 0, 'message'=>'Thất bại']);
        }
    }
}

resources/views/backend/banner/create.blade.php
@extends('backend.layout.main')

@section('content')
    <section class="content-header">
        <h1>
           Quản Lý Danh Sách Banner 
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Trang chủ</a></li>
            
            <li class="active">Quản lý Banner</li>
        </ol>
    </section>
    <section class="content">
      <div class="row">
        <!-- left column -->
        <div class="col-md-12">
          <!-- general form elements -->
          <div class="box box-primary">
            <div class="box-header with-border">
              <h3 class="box-title"> Thêm Thông Tin Banner </h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
        <form role="form" method="post" action="{{route('admin.banner.store')}} " enctype="multipart/form-data">
        @csrf
        
              <div class="box-body"> 

                    <div class="col-md-6">

                        <!-- <div class="form-group" name="parent_id" id ="parent_id"> 
                            <label>Loại Danh Mục</label>
                            <select class="form-control">
                              <option>0</option>
                              <option>1</option>
                              <option>4</option>
                              <option>5</option>
                              <option>6</option>
                              
                            </select>
                          </div> -->

                          <!-- <div class="form-group" name="text" id ="text"> 
                            <label> Loại Danh Mục </label>
                            <select class="form-control">
                              <option> Menu </option>
                              <option>Bài Viết</option>
                              <option>Sản Phẩm</option>
                              
                            </select>
                          </div> -->

                        <div class="form-group">
                              <label for="exampleInputEmail1">Tên Banner</label>
                              <input required type="text" class="form-control" id="title" name="title" placeholder="Nhập tên danh mục">
                            @if($errors->has('title'))
                              <label class="Text-red" style="font-size:15px;font-weight:600;margin-top:5px" >
                                    <i class="fa fa-info"></i>{{$errors->first('title')}}
                              </label>
                            @endif
                        </div>

                        <div class="form-group">
                              <label for="exampleInputEmail1">Slug </label>
                              <input required type="text" class="form-control" id="slug" name="slug" placeholder="Nhập tên slug">
                              @if($errors->has('slug'))
                              <label class="Text-red" style="font-size:15px;font-weight:600;margin-top:5px" >
                                    <i class="fa fa-info"></i>{{$errors->first('slug')}}
                              </label>
                            @endif  
                        </div>

                        <div class="form-group">
                              <label for="exampleInputEmail1">Ngày Thêm</label>
                              <input required type="date" class="form-control" id="created_at" name="created_at" placeholder="Nhập ngày thêm">
                        </div>

                        <div class="form-group">
                                  <label for="exampleInputFile">Avatar</label>
                                  <input type="file" id="image" name="image" >

                                  @if($errors->has('image'))
                              <label class="Text-red" style="font-size:15px;font-weight:600;margin-top:5px" >
                                    <i class="fa fa-info"></i>{{$errors->first('image')}}
                              </label>
                            @endif  

                        </div>

                        <!-- <div class="form-group">
                                  <label for="exampleInputEmail1">Vị trí hiển thị </label>
                                  <input required type="number" class="form-control" id="position" name="position" min="1">
                        </div> -->
                                            
                        <div class="checkbox">
                                  <label>
                                      <input type="checkbox"  name="is_active" id="is_active" > Hiển thị
                                  </label>
                       </div>
               

                    </div>

                      

              </div>
              

               <div class="box-footer">
                  <button type="submit" class="btn btn-primary" > Thêm  </button>
              </div>
        </form>
        </div>

      </div>
       
    </section>
@endsection

@section('js')
<script>  
$('#title').keyup(function(event) {
  var title, slug;
 
    //Lấy text từ thẻ input title 
   title = document.getElementById("title").value;
 
    //Đổi chữ hoa thành chữ thường
    slug = title.toLowerCase();
 
    //Đổi ký tự có dấu thành không dấu
    slug = slug.replace(/á|à|ả|ạ|ã|ă|ắ|ằ|ẳ|ẵ|ặ|â|ấ|ầ|ẩ|ẫ|ậ/gi, 'a');
    slug = slug.replace(/é|è|ẻ|ẽ|ẹ|ê|ế|ề|ể|ễ|ệ/gi, 'e');
    slug = slug.replace(/i|í|ì|ỉ|ĩ|ị/gi, 'i');
    slug = slug.replace(/ó|ò|ỏ|õ|ọ|ô|ố|ồ|ổ|ỗ|ộ|ơ|ớ|ờ|ở|ỡ|ợ/gi, 'o');
    slug = slug.replace(/ú|ù|ủ|ũ|ụ|ư|ứ|ừ|ử|ữ|ự/gi, 'u');
    slug = slug.replace(/ý|ỳ|ỷ|ỹ|ỵ/gi, 'y');
    slug = slug.replace(/đ/gi, 'd');
    //Xóa các ký tự đặt biệt
    slug = slug.replace(/\`|\~|\!|\@|\#|\||\$|\%|\^|\&|\*|\(|\)|\+|\=|\,|\.|\/|\?|\>|\<|\'|\"|\:|\;|_/gi, '');
    //Đổi khoảng trắng thành ký tự gạch ngang
    slug = slug.replace(/ /gi, " - ");
    //Đổi nhiều ký tự gạch ngang liên tiếp thành 1 ký tự gạch ngang
    //Phòng trường hợp người nhập vào quá nhiều ký tự trắng
    slug = slug.replace(/\-\-\-\-\-/gi, '-');
    slug = slug.replace(/\-\-\-\-/gi, '-');
    slug = slug.replace(/\-\-\-/gi, '-');
    slug = slug.replace(/\-\-/gi, '-');
    //Xóa các ký tự gạch ngang ở đầu và cuối
    slug = '@' + slug + '@';
    slug = slug.replace(/\@\-|\-\@|\@/gi, '');
    //In slug ra textbox có id “slug”
    $('#slug').val(slug);
});
      

</script>
@endsection

resources/views/backend/banner/edit.blade.php
@extends('backend.layout.main')

@section('content')
    <section class="content-header">
        <h1>
            Chỉnh Sửa Banner <a href="{{route('admin.banner.index')}}" class="btn btn-primary"> Danh Sách</a>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Trang chủ</a></li>
            
            <li class="active">Sửa Banner</li>
        </ol>
    </section>
    <section class="content">
      <div class="row">
        <!-- left column -->
        <div class="col-md-12">
          <!-- general form elements -->
          <div class="box box-primary">
            <div class="box-header with-border">
              <h3 class="box-title"> Sửa Thông Tin Banner </h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
        <form role="form" method="post" action="{{route('admin.banner.update',['id'=>$banner->id])}} " enctype="multipart/form-data">
        @csrf
        
        @method('PUT')
              <div class="box-body"> 

                    <div class="col-md-6">

                        <!-- <div class="form-group" name="parent_id" id ="parent_id"> 
                            <label>Loại Danh Mục</label>
                            <select class="form-control">
                              <option>0</option>
                              <option>1</option>
                              <option>4</option>
                              <option>5</option>
                              <option>6</option>
                              
                            </select>
                          </div> -->

                          <!-- <div class="form-group" name="text" id ="text"> 
                            <label> Loại Danh Mục </label>
                            <select class="form-control">
                              <option> Menu </option>
                              <option>Bài Viết</option>
                              <option>Sản Phẩm</option>
                              
                            </select>
                          </div> -->

                        <div class="form-group">
                              <label for="exampleInputEmail1">Sửa Tên Banner</label>
                              <input required type="text" class="form-control" id="title" name="title" placeholder="Nhập tên danh mục" value="{{$banner->title}}">
                            @if($errors->has('title'))
                              <label class="Text-red" style="font-size:15px;font-weight:600;margin-top:5px" >
                                    <i class="fa fa-info"></i>{{$errors->first('title')}}
                              </label>
                            @endif
                        </div>

                        <div class="form-group">
                              <label for="exampleInputEmail1">Slug </label>
                              <input required type="text" class="form-control" id="slug" name="slug" placeholder="Nhập tên slug">
                              @if($errors->has('slug'))
                              <label class="Text-red" style="font-size:15px;font-weight:600;margin-top:5px" >
                                    <i class="fa fa-info"></i>{{$errors->first('slug')}}
                              </label>
                            @endif  
                        </div>

                        <div class="form-group">
                              <label for="exampleInputEmail1">Ngày Thêm </label>
                              <input required type="date" class="form-control" id="created_at" name="created_at" placeholder="Nhập ngày thêm" value="{{$banner->created_at}}">
                        </div>

                        <div class="form-group">
                                  <label for="exampleInputFile">Avatar</label>
                                  <input type="file" id="image" name="image"  >
                                  <img src="{{ asset($banner->image) }}" alt="" width="100" style="margin-top: 10px;">

                                  @if($errors->has('image'))
                              <label class="Text-red" style="font-size:15px;font-weight:600;margin-top:5px" >
                                    <i class="fa fa-info"></i>{{$errors->first('image')}}
                              </label>
                            @endif  

                        </div>
                    
                        <div class="checkbox">
                                  <label>
                                      <input type="checkbox"  name="is_active" id="is_active" > Hiển thị
                                  </label>
                       </div>
               
                    </div>

              </div>
              

               <div class="box-footer">
                  <button type="submit" class="btn btn-primary" > Lưu  </button>
              </div>
        </form>
        </div>

      </div>
       
    </section>
@endsection

@section('js')
<script>  
$('#title').keyup(function(event) {
  var title, slug;
 
    //Lấy text từ thẻ input title 
   title = document.getElementById("title").value;
 
    //Đổi chữ hoa thành chữ thường
    slug = title.toLowerCase();
 
    //Đổi ký tự có dấu thành không dấu
    slug = slug.replace(/á|à|ả|ạ|ã|ă|ắ|ằ|ẳ|ẵ|ặ|â|ấ|ầ|ẩ|ẫ|ậ/gi, 'a');
    slug = slug.replace(/é|è|ẻ|ẽ|ẹ|ê|ế|ề|ể|ễ|ệ/gi, 'e');
    slug = slug.replace(/i|í|ì|ỉ|ĩ|ị/gi, 'i');
    slug = slug.replace(/ó|ò|ỏ|õ|ọ|ô|ố|ồ|ổ|ỗ|ộ|ơ|ớ|ờ|ở|ỡ|ợ/gi, 'o');
    slug = slug.replace(/ú|ù|ủ|ũ|ụ|ư|ứ|ừ|ử|ữ|ự/gi, 'u');
    slug = slug.replace(/ý|ỳ|ỷ|ỹ|ỵ/gi, 'y');
    slug = slug.replace(/đ/gi, 'd');
    //Xóa các ký tự đặt biệt
    slug = slug.replace(/\`|\~|\!|\@|\#|\||\$|\%|\^|\&|\*|\(|\)|\+|\=|\,|\.|\/|\?|\>|\<|\'|\"|\:|\;|_/gi, '');
    //Đổi khoảng trắng thành ký tự gạch ngang
    slug = slug.replace(/ /gi, " - ");
    //Đổi nhiều ký tự gạch ngang liên tiếp thành 1 ký tự gạch ngang
    //Phòng trường hợp người nhập vào quá nhiều ký tự trắng
    slug = slug.replace(/\-\-\-\-\-/gi, '-');
    slug = slug.replace(/\-\-\-\-/gi, '-');
    slug = slug.replace(/\-\-\-/gi, '-');
    slug = slug.replace(/\-\-/gi, '-');
    //Xóa các ký tự gạch ngang ở đầu và cuối
    slug = '@' + slug + '@';
    slug = slug.replace(/\@\-|\-\@|\@/gi, '');
    //In slug ra textbox có id “slug”
    $('#slug').val(slug);
});
      

</script>
@endsection

resources/views/backend/banner/index.blade.php
@extends('backend.layout.main')

@section('content')
    <section class="content-header">
        <h1>
           Quản Lý Banner <a href="{{route('admin.banner.create')}}" class="btn btn-primary"> Thêm Banner </a>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Trang chủ</a></li>
            
            <li class="active">Quản lý Banner</li>
        </ol>
    </section>
    <section class="content">
    <div class="col-md-12">
          <div class="box">
            <div class="box-header with-border">
              <h3 class="box-title"> Danh Sách Banner</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              <table class="table table-bordered">
                <tr>
                  <th style="width: 10px">STT</th>
                  <th> Image </th>
                  <th> Title </th>
                  <th>Slug</th>
                  <th>Ngày cấp</th>
                  <th> Trạng thái </th>
                  <th> Chức năng</th>
                </tr>

                @foreach($banner as $key => $row)
                    <tr >
                        <td>{{$key +1 }}</td>
                        <td> <img src="{{ asset($row->image) }}" height="50"></td>
                        <td>{{$row->title}}</td>
                        <td>{{$row->slug}}</td>
                        <td>{{$row->created_at}}</td>
                        <td>{{ $row->is_active == 1 ? 'Show' : 'Hide' }}</td>
                        <td class="text-center">
                            <a href="{{route('admin.banner.edit',['id'=>$row->id])}}" class="btn btn-flat bg-purple"><i class="fa fa-pencil"></i></a>
                            <button data-id="{{$row->id}}" class="btn btn-danger btn-delete"><i class="fa fa-trash"></i></button>
                         </td>
                    
                    </tr>


                @endforeach
             </table>

            </div>
            <div class="box-footer clearfix">
                        {{ $banner->links() }}
                    </div>
            
            </div>
    </div>
        
       
    </section>
@endsection

@section('category_js')

<script type="text/javascript">
        $(document).ready(function() {
            // Thiết lập csrf => chổng giả mạo
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN' : $('meta[name="csrf-token"]').attr('content')
                }
            })

            $('.btn-delete').on('click',function () {

                let id = $(this).data('id');

                let result = confirm("Bạn có chắc chắn muốn xóa ?");

                if (result) { // neu nhấn == ok , sẽ send request ajax

                    $.ajax({
                        url: '/admin/banner/'+id, // http://webthucpham.local:8888/user/8
                        type: 'DELETE', // phương truyền tải dữ liệu
                        data: {
                            // dữ liệu truyền sang nếu có
                            name : 'dung'
                        },
                        dataType: "json", // kiểu dữ liệu muốn nhận về
                        success: function (res) {
                            //  PHP : $user->name
                            //  JS: res.name

                            if (res.success != 'undefined' && res.success == 1) { // xóa thành công
                                $('.item-'+id).remove();
                            }
                            window.location.href = '/admin/banner';
                        },
                        error: function (e) { // lỗi nếu có
                            console.log(e);
                        }
                    });
                }

            });

           
        });
    </script>

@endsection