routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/','ShopController@index')->name('shop.index');

Route::get('/lien-he', 'ShopController@contact')->name('shop.contact');
Route::post('/lien-he', 'ShopController@postContact')->name('shop.postContact');

Route::get('/index','ShopController@index')->name('shop.index');

Route::get('/Category/{type}','ShopController@Category')->name('shop.category');
Route::get('/chitietsanpham/{id}','ShopController@Chitietsanpham')->name('shop.chitietsanpham');
Route::get('/article','ShopController@Articles')->name('shop.article');
Route::get('/tim-kiem','ShopController@Seach')->name('shop.timkiem');
Route::get('/dang-ky','ShopController@Register')->name('shop.register');
Route::post('dang-ky','ShopController@postRegister')->name('shop.postRegister');
Route::get('/dang-nhap','ShopController@Login')->name('shop.Login');
Route::post('dang-nhap','ShopController@postLogin')->name('shop.postLogin');

Route::get('/admin/logout', 'ShopController@logout')->name('admin.logout');

// //trang danh sách giỏ hàng
Route::get('/danhsachgiohang','CartController@index')->name('cart.index');

//thêm sản phẩm vào giỏ hàng
Route::get('/giohang/{id}','CartController@addtoCart')->name('cart.addcart');

Route::get('Delete-cart/{id}','CartController@DeleteCart')->name('delete.cart');

Route::get('cap-nhap-so-luong-sp','CartController@updateCart')->name('update.cart');
Route::get('huy-don-hang','CartController@destroy')->name('destroy.cart');

Route::get('order-product','ShopController@OrderProduct')->name('order.product');







Route::get('/admin', 'AdminController@login')->name('admin.index');
Route::get('/admin/login', 'AdminController@login')->name('admin.login');
Route::post('/admin/login', 'AdminController@postLogin')->name('admin.postLogin');






Route::group(['prefix' => 'admin','as'=>'admin.'], function(){
    Route::post('/store','LoginController@store');
    Route::resource('photo', 'PhotoController');
    Route::resource('vendor', 'VendorController');
    Route::resource('category', 'CategoryController');
    Route::resource('user','UserController');
    Route::resource('banner','BannerController');
    Route::resource('product','ProductController');
    Route::resource('article','ArticlesController');
    Route::resource('setting', 'settingController');
    Route::resource('contact', 'ContactController');
});

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $fillable = [
        'name','category_id','slug','image','stock','price','sale','created_at',
    ];

    public function category()
    {
        return $this->belongsTo('App\Category');
    }
    // public function post()
    // {
    //     return $this->belongsTo('App\Post');
    // }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Product;
use App\Category;

use Illuminate\Support\Facades\DB;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $product = DB::table('products')->select('*');
        $product = $product ->get();
        $product = Product::latest()->paginate(10);
        return view('backend.product.index',compact('product'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $category = Category::all();

        return view('backend.product.create',compact('category'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' =>'required',
            'slug' =>'required',
            'created_at'=> 'required',
            'image' => 'required',
            'stock'=>'required',
            'price'=>'required',
            'sale'=>'required',

        ]);

        $name = $request->input('name');
        $category = $request->input('category_id');
        $slug = $request->input('slug');
        $stock = $request->input('stock');
        $price = $request->input('price');
        $sale = $request->input('sale');

        $is_active = 0; // default
        if ($request->has('is_active')) {
            $is_active = (int) $request->input('is_active');
        }

        $path_avatar = '';
        if ($request->hasFile('image')) {
            // get file
            $file = $request->file('image');
            // get ten
            $filename = $file->getClientOriginalName(); // lấy tên gốc của ảnh
            // duong dan upload
            $path_upload = 'upload/product/';
            // upload file
            $file->move($path_upload, $filename);
            $path_avatar = $path_upload.$filename;

            $pro = new Product();
            $pro ->name = $name;
            $pro->category_id=$category;
            $pro->slug=$slug;
            $pro->image = $path_avatar;
            $pro->stock = $stock;
            $pro->price = $price;
            $pro->sale = $sale;


            //lưu
            $pro->save();
                // chuyển hướng điều trang
            return redirect()->route('admin.product.index');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $product = Product::find($id);
        $category = Category::all();
        return view('backend.product.edit', compact('product','category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $request->validate([
            'name' =>'required',
            'slug' =>'required',
            'created_at'=> 'required',
            'image' => 'required',
            'stock'=>'required',
            'price'=>'required',
            'sale'=>'required',

        ]);
        // dd($request->all());
        $name = $request->input('name');
        $category = $request->input('category_id');
        $slug = $request->input('slug');
        $stock = $request->input('stock');
        $price = $request->input('price');
        $sale = $request->input('sale');

        $is_active = 0; // default
        if ($request->has('is_active')) {
            $is_active = (int) $request->input('is_active');
        }

        $path_avatar = '';
        if ($request->hasFile('image')) {
            // get file
            $file = $request->file('image');
            // get ten
            $filename = $file->getClientOriginalName(); // lấy tên gốc của ảnh
            // duong dan upload
            $path_upload = 'upload/product/';
            // upload file
            $file->move($path_upload, $filename);
            $path_avatar = $path_upload.$filename;

            $pro = Product::find($id);


            $pro->name = $name;
            $pro->category_id=$category;
            $pro->slug=$slug;
            $pro->image = $path_avatar;
            $pro->stock = $stock;
            $pro->price = $price;
            $pro->sale = $sale;


            //lưu
            $pro->save();
            // chuyển hướng điều trang
            return redirect()->route('admin.product.index');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $isDelete = Product ::destroy($id);

        if ($isDelete) { // xóa thành công
            return response()->json(['isSuccess' => 1,'message'=>'Thành công']);
        } else {
            return response()->json(['isSuccess' => 0, 'message'=>'Thất bại']);
        }
    }
}

resources/views/backend/product/create.blade.php
@extends('backend.layout.main')

@section('content')
    <section class="content-header">
        <h1>
           Quản Lý Sản Phẩm
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Trang chủ</a></li>
            
            <li class="active">Quản lý sản phẩm</li>
        </ol>
    </section>
    <section class="content">
      <div class="row">
        <!-- left column -->
        <div class="col-md-12">
          <!-- general form elements -->
          <div class="box box-primary">
            <div class="box-header with-border">
              <h3 class="box-title"> Thêm Thông Tin  Sản Phẩm </h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
        <form role="form" method="post" action="{{route('admin.product.store')}} " enctype="multipart/form-data">
        @csrf
        
              <div class="box-body"> 

                    <div class="col-md-6">

                        <div class="form-group" name="category_id" id ="category_id"> 
                            <label>Danh mục sản phẩm</label>
                            <select class="form-control" name="category_id" >
                                <option value="select"> -- chọn Danh Mục --</option>
                                   @foreach($category as $cat)
                                      <option value="{{ $cat->id }}">{{ $cat->name }}</option>
                                     @endforeach
                             </select>
                          </div>

                          

                        <div class="form-group">
                              <label for="exampleInputEmail1">Tên sản phẩm</label>
                              <input required type="text" class="form-control" id="name" name="name" placeholder="Nhập tên danh mục">
                            @if($errors->has('name'))
                              <label class="Text-red" style="font-size:15px;font-weight:600;margin-top:5px" >
                                    <i class="fa fa-info"></i>{{$errors->first('name')}}
                              </label>
                            @endif
                        </div>

                        <div class="form-group">
                              <label for="exampleInputEmail1">Slug </label>
                              <input required type="text" class="form-control" id="slug" name="slug" placeholder="Nhập tên slug">
                              @if($errors->has('slug'))
                              <label class="Text-red" style="font-size:15px;font-weight:600;margin-top:5px" >
                                    <i class="fa fa-info"></i>{{$errors->first('slug')}}
                              </label>
                            @endif  
                        </div>

                        <div class="form-group">
                              <label for="exampleInputEmail1">Số lượng trong kho </label>
                              <input required type="text" class="form-control" id="stock" name="stock" placeholder="Nhập số lượng">
                            @if($errors->has('stock'))
                              <label class="Text-red" style="font-size:15px;font-weight:600;margin-top:5px" >
                                    <i class="fa fa-info"></i>{{$errors->first('stock')}}
                              </label>
                            @endif
                        </div>

                        <div class="form-group">
                              <label for="exampleInputEmail1"> Giá Gốc(vnđ) </label>
                              <input required type="number" class="form-control" id="price" name="price" placeholder="Nhập tên giá gốc">
                            @if($errors->has('price'))
                              <label class="Text-red" style="font-size:15px;font-weight:600;margin-top:5px" >
                                    <i class="fa fa-info"></i>{{$errors->first('price')}}
                              </label>
                            @endif
                        </div>

                        <div class="form-group">
                              <label for="exampleInputEmail1"> Giá Khuyến mãi(vnđ) </label>
                        <input required type="number" class="form-control" id="sale" name="sale" placeholder="Nhập giá khuyến mãi">
                            @if($errors->has('sale'))
                              <label class="Text-red" style="font-size:15px;font-weight:600;margin-top:5px" >
                                    <i class="fa fa-info"></i>{{$errors->first('sale')}}
                              </label>
                            @endif
                        </div>

                        <div class="form-group">
                              <label for="exampleInputEmail1">Ngày Thêm</label>
                              <input required type="date" class="form-control" id="name" name="created_at" placeholder="Nhập ngày thêm">
                        </div>

                        <div class="form-group">
                                  <label for="exampleInputFile">Avatar Sản Phẩm</label>
                                  <input type="file" id="image" name="image" >
                                  

                                  @if($errors->has('image'))
                              <label class="Text-red" style="font-size:15px;font-weight:600;margin-top:5px" >
                                    <i class="fa fa-info"></i>{{$errors->first('image')}}
                              </label>
                            @endif  

                        </div>

                        <div class="form-group">
                                  <label for="exampleInputEmail1">Vị trí hiển thị </label>
                                  <input required type="number" class="form-control" id="position" name="position" min="1">
                        </div>
                      
                        <div class="form-group">
                                  <label for="exampleInputEmail1">Tóm Tắt </label>
                                  <textarea  id="summary" name="summary" class="form-control" rows="3"
                                          placeholder="Enter ..."></textarea>
                        </div>
                        
                        <div class="form-group">
                                  <label for="exampleInputEmail1"> Mô Tả </label>
                                  <textarea id="summary" name="summary" class="form-control" rows="3"
                                          placeholder="Enter ..."></textarea>
                        </div>

                                            
                        <div class="checkbox">
                                  <label>
                                      <input type="checkbox"  name="is_active" id="is_active" > Hiển thị
                                  </label>
                       </div>
               

                    </div>

              </div>
              

               <div class="box-footer">
                  <button type="submit" class="btn btn-primary" > Thêm  </button>
              </div>
        </form>
        </div>

      </div>
       
    </section>
@endsection

@section('js')
<script>  
$('#title').keyup(function(event) {
  var title, slug;
 
    //Lấy text từ thẻ input title 
   title = document.getElementById("title").value;
 
    //Đổi chữ hoa thành chữ thường
    slug = title.toLowerCase();
 
    //Đổi ký tự có dấu thành không dấu
    slug = slug.replace(/á|à|ả|ạ|ã|ă|ắ|ằ|ẳ|ẵ|ặ|â|ấ|ầ|ẩ|ẫ|ậ/gi, 'a');
    slug = slug.replace(/é|è|ẻ|ẽ|ẹ|ê|ế|ề|ể|ễ|ệ/gi, 'e');
    slug = slug.replace(/i|í|ì|ỉ|ĩ|ị/gi, 'i');
    slug = slug.replace(/ó|ò|ỏ|õ|ọ|ô|ố|ồ|ổ|ỗ|ộ|ơ|ớ|ờ|ở|ỡ|ợ/gi, 'o');
    slug = slug.replace(/ú|ù|ủ|ũ|ụ|ư|ứ|ừ|ử|ữ|ự/gi, 'u');
    slug = slug.replace(/ý|ỳ|ỷ|ỹ|ỵ/gi, 'y');
    slug = slug.replace(/đ/gi, 'd');
    //Xóa các ký tự đặt biệt
    slug = slug.replace(/\`|\~|\!|\@|\#|\||\$|\%|\^|\&|\*|\(|\)|\+|\=|\,|\.|\/|\?|\>|\<|\'|\"|\:|\;|_/gi, '');
    //Đổi khoảng trắng thành ký tự gạch ngang
    slug = slug.replace(/ /gi, " - ");
    //Đổi nhiều ký tự gạch ngang liên tiếp thành 1 ký tự gạch ngang
    //Phòng trường hợp người nhập vào quá nhiều ký tự trắng
    slug = slug.replace(/\-\-\-\-\-/gi, '-');
    slug = slug.replace(/\-\-\-\-/gi, '-');
    slug = slug.replace(/\-\-\-/gi, '-');
    slug = slug.replace(/\-\-/gi, '-');
    //Xóa các ký tự gạch ngang ở đầu và cuối
    slug = '@' + slug + '@';
    slug = slug.replace(/\@\-|\-\@|\@/gi, '');
    // slug = slug.replace(' ','');
    //In slug ra textbox có id “slug”
    $('#slug').val(slug);
});
      

</script>
@endsection

@section('my_js')

<script type="text/javascript">
      $(function () {
            var _ckeditor = CKEDITOR.replace('summary');
            _ckeditor.config.height = 200; // thiết lập chiều cao
            var _ckeditor = CKEDITOR.replace('description');
            _ckeditor.config.height = 600; // thiết lập chiều cao
        })
</script>
@endsection

resources/views/backend/product/edit.blade.php
@extends('backend.layout.main')

@section('content')
    <section class="content-header">
        <h1>
           Chỉnh sửa thông tin sản phẩm <a href="{{route('admin.product.index')}}" class="btn btn-primary"> Danh Sách</a>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Trang chủ</a></li>
            
            <li class="active">Quản lý danh mục</li>
        </ol>
    </section>
    <section class="content">
      <div class="row">
        <!-- left column -->
        <div class="col-md-12">
          <!-- general form elements -->
          <div class="box box-primary">
            <div class="box-header with-border">
              <h3 class="box-title">  Thông Tin Sản Phẩm  </h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
        <form role="form" method="post" action="{{route('admin.product.update',['id'=>$product->id])}} " enctype="multipart/form-data">
        @csrf
        @method('PUT')
        
              <div class="box-body"> 

                    <div class="col-md-6">

                    <div class="form-group" name="category_id" id ="category_id"> 
                            <label>Thay đổi Danh mục sản phẩm</label>
                            <select class="form-control" name="category_id"  >
                                <option value="select"> -- chọn Danh Mục --</option>
                                   @foreach($category as $cat)
                                      <option value="{{ $cat->id }}" {{ ($product->category_id == $cat->id) ? 'selected' : '' }} >{{ $cat->name }}</option>
                                    @endforeach
                             </select>
                          </div>

                          

                        <div class="form-group">
                              <label for="exampleInputEmail1">Tên sản phẩm</label>
                              <input required type="text" class="form-control" id="name" name="name" placeholder="Nhập tên danh mục" value="{{$product->name}}">
                            @if($errors->has('name'))
                              <label class="Text-red" style="font-size:15px;font-weight:600;margin-top:5px" >
                                    <i class="fa fa-info"></i>{{$errors->first('name')}}
                              </label>
                            @endif
                        </div>

                        <div class="form-group">
                              <label for="exampleInputEmail1">Slug </label>
                              <input required type="text" class="form-control" id="slug" name="slug" placeholder="Nhập tên slug" value="{{$product->slug}}">
                              @if($errors->has('slug'))
                              <label class="Text-red" style="font-size:15px;font-weight:600;margin-top:5px" >
                                    <i class="fa fa-info"></i>{{$errors->first('slug')}}
                              </label>
                            @endif  
                        </div>

                        <div class="form-group">
                              <label for="exampleInputEmail1">Số lượng trong kho </label>
                              <input required type="text" class="form-control" id="stock" name="stock" placeholder="Nhập số lượng" value="{{$product->stock}}">
                            @if($errors->has('stock'))
                              <label class="Text-red" style="font-size:15px;font-weight:600;margin-top:5px" >
                                    <i class="fa fa-info"></i>{{$errors->first('stock')}}
                              </label>
                            @endif
                        </div>

                        <div class="form-group">
                              <label for="exampleInputEmail1"> Giá Gốc(vnđ) </label>
                              <input required type="number" class="form-control" id="price" name="price" placeholder="Nhập tên giá gốc" value="{{$product->price}}">
                            @if($errors->has('price'))
                              <label class="Text-red" style="font-size:15px;font-weight:600;margin-top:5px" >
                                    <i class="fa fa-info"></i>{{$errors->first('price')}}
                              </label>
                            @endif
                        </div>

                        <div class="form-group">
                              <label for="exampleInputEmail1"> Giá Khuyến mãi(vnđ) </label>
                              <input required type="number" class="form-control" id="sale" name="sale" placeholder="Nhập giá khuyến mãi" value="{{$product->sale}}">
                            @if($errors->has('sale'))
                              <label class="Text-red" style="font-size:15px;font-weight:600;margin-top:5px" >
                                    <i class="fa fa-info"></i>{{$errors->first('sale')}}
                              </label>
                            @endif
                        </div>

                        <div class="form-group">
                              <label for="exampleInputEmail1">Ngày Thêm</label>
                              <input required type="date" class="form-control" id="created_at" name="created_at" placeholder="Nhập ngày thêm" value="{{$product->created_at}}">
                        </div>

                        <div class="form-group">
                                  <label for="exampleInputFile">Avatar Sản Phẩm Mới</label>
                                  <input type="file" id="image" name="image" >
                                  <img src="{{ asset($product->image) }}" alt="" width="100" style="margin-top: 10px;">
                                  

                                  @if($errors->has('image'))
                              <label class="Text-red" style="font-size:15px;font-weight:600;margin-top:5px" >
                                    <i class="fa fa-info"></i>{{$errors->first('image')}}
                              </label>
                            @endif  

                        </div>

                        <div class="form-group">
                                  <label for="exampleInputEmail1">Vị trí hiển thị </label>
                                  <input required type="number" class="form-control" id="position" name="position" min="1">
                        </div>
                                            
                        <div class="checkbox">
                                  <label>
                                      <input type="checkbox"  name="is_active" id="is_active" > Hiển thị
                                  </label>
                       </div>
               
                                            
                        <div class="checkbox">
                                  <label>
                                      <input {{ ($product->is_active == 1) ? 'checked' : '' }} type="checkbox"  name="is_active" id="is_active" > Kích Hoạt
                                  </label>
                       </div>
               

                    </div>

                    
              </div>
              

               <div class="box-footer">
                  <button type="submit" class="btn btn-primary" > Lưu  </button>
              </div>
        </form>
        </div>

      </div>
       
    </section>
@endsection

@section('js')
<script>  
$('#name').keyup(function(event) {
  var title, slug;
 
    //Lấy text từ thẻ input title 
   title = document.getElementById("name").value;
 
    //Đổi chữ hoa thành chữ thường
    slug = title.toLowerCase();
 
    //Đổi ký tự có dấu thành không dấu
    slug = slug.replace(/á|à|ả|ạ|ã|ă|ắ|ằ|ẳ|ẵ|ặ|â|ấ|ầ|ẩ|ẫ|ậ/gi, 'a');
    slug = slug.replace(/é|è|ẻ|ẽ|ẹ|ê|ế|ề|ể|ễ|ệ/gi, 'e');
    slug = slug.replace(/i|í|ì|ỉ|ĩ|ị/gi, 'i');
    slug = slug.replace(/ó|ò|ỏ|õ|ọ|ô|ố|ồ|ổ|ỗ|ộ|ơ|ớ|ờ|ở|ỡ|ợ/gi, 'o');
    slug = slug.replace(/ú|ù|ủ|ũ|ụ|ư|ứ|ừ|ử|ữ|ự/gi, 'u');
    slug = slug.replace(/ý|ỳ|ỷ|ỹ|ỵ/gi, 'y');
    slug = slug.replace(/đ/gi, 'd');
    //Xóa các ký tự đặt biệt
    slug = slug.replace(/\`|\~|\!|\@|\#|\||\$|\%|\^|\&|\*|\(|\)|\+|\=|\,|\.|\/|\?|\>|\<|\'|\"|\:|\;|_/gi, '');
    //Đổi khoảng trắng thành ký tự gạch ngang
    slug = slug.replace(/ /gi, " - ");
    //Đổi nhiều ký tự gạch ngang liên tiếp thành 1 ký tự gạch ngang
    //Phòng trường hợp người nhập vào quá nhiều ký tự trắng
    slug = slug.replace(/\-\-\-\-\-/gi, '-');
    slug = slug.replace(/\-\-\-\-/gi, '-');
    slug = slug.replace(/\-\-\-/gi, '-');
    slug = slug.replace(/\-\-/gi, '-');
    //Xóa các ký tự gạch ngang ở đầu và cuối
    slug = '@' + slug + '@';
    slug = slug.replace(/\@\-|\-\@|\@/gi, '');
    //In slug ra textbox có id “slug”
    $('#slug').val(slug);
});
      

</script>
@endsection

resources/views/backend/product/index.blade.php
@extends('backend.layout.main')

@section('content')
    <section class="content-header">
        <h1>
            Quản Lý Sản Phẩm <a href="{{ route('admin.product.create') }}" class="btn bg-purple btn-flat"><i class="fa fa-plus"></i> Thêm Sản Phẩm</a>
        </h1>
        <ol class="breadcrumb">
            <li><a href="/"><i class="fa fa-dashboard"></i> Trang chủ</a></li>
            <li class="active">Quản Lý Sản Phẩm</li>
        </ol>
    </section>

    <section class="content">
        <div class="row">
            <div class="col-md-12">
                <div class="box">
                    <div class="box-header with-border">
                        <h3 class="box-title">Danh Sách Sản Phẩm </h3>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <table class="table table-bordered">
                            <tbody>
                            <tr>
                                <th style="width: 10px">STT</th>
                                <th>Image</th>
                                <th>Name</th>
                                <th> Category</th>
                                <th>Slug</th>
                                <th>Stock</th>
                                <th>Price</th>
                                <th>Sale</th>
                                <th>Ngày Cấp</th>
                                <th>Trạng Thái</th>
                                <th>Hành Động</th>

                            </tr>

                            @foreach($product as $key => $item)
                                <tr class="item-{{ $item->id }}">
                                    <td>{{ $key +1 }}</td>
                                    <td><img src="{{ asset($item->image) }}" width="50" height="75" /></td>
                                    <td>{{ $item->name }}</td>
                                    <td>{{ @$item->category->name }}</td>
                                      
                                    <td>{{ $item->slug }}</td>
                                    <td>{{ $item->stock }}</td>
                                    <td>{{ $item->price }}</td>
                                    <td>{{ $item->sale }}</td>
                                    <td>{{ $item->created_at }}</td>
                                    <td>{{ $item->is_active == 1 ? 'Show' : 'Hide' }}</td>
                                    <td class="text-center">
                                        <a href="{{route('admin.product.edit',['id'=> $item -> id])}}" class="btn btn-flat bg-purple"><i class="fa fa-pencil"></i></a>
                                        <button data-id="{{$item->id}}" class="btn btn-danger btn-delete"><i class="fa fa-trash"></i></button>
                                    </td>
                                </tr>

                            @endforeach

                            </tbody>
                        </table>

                    </div>
                    <!-- /.box-body -->
                    <div class="box-footer clearfix">
                        {{ $product->links() }}
                    </div>
                </div>
                <!-- /.box -->
            </div>
            <!-- /.col -->
        </div>
    </section>
@endsection

@section('my_js')
    <script type="text/javascript">
        $(document).ready(function() {
            // Thiết lập csrf => chổng giả mạo
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN' : $('meta[name="csrf-token"]').attr('content')
                }
            })

            $('.btn-delete').on('click',function () {

                let id = $(this).data('id');

                let result = confirm("Bạn có chắc chắn muốn xóa ?");

                if (result) { // neu nhấn == ok , sẽ send request ajax

                    $.ajax({
                        url: '/admin/product/'+id, // http://webthucpham.local:8888/user/8
                        type: 'DELETE', // phương truyền tải dữ liệu
                        data: {
                            // dữ liệu truyền sang nếu có
                            name : 'dung'
                        },
                        dataType: "json", // kiểu dữ liệu muốn nhận về
                        success: function (res) {
                            //  PHP : $user->name
                            //  JS: res.name

                            if (res.success != 'undefined' && res.success == 1) { // xóa thành công
                                $('.item-'+id).remove();
                            }
                            window.location.href = '/admin/product/';
                        },
                        error: function (e) { // lỗi nếu có
                            console.log(e);
                        }
                    });
                }

            });

            /*$( ".btn-delete" ).click(function() {
                alert( "Handler for .click() called." );
            });*/

        });
    </script>
@endsection