routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/','ShopController@index')->name('shop.index');

Route::get('/lien-he', 'ShopController@contact')->name('shop.contact');
Route::post('/lien-he', 'ShopController@postContact')->name('shop.postContact');

Route::get('/index','ShopController@index')->name('shop.index');

Route::get('/Category/{type}','ShopController@Category')->name('shop.category');
Route::get('/chitietsanpham/{id}','ShopController@Chitietsanpham')->name('shop.chitietsanpham');
Route::get('/article','ShopController@Articles')->name('shop.article');
Route::get('/tim-kiem','ShopController@Seach')->name('shop.timkiem');
Route::get('/dang-ky','ShopController@Register')->name('shop.register');
Route::post('dang-ky','ShopController@postRegister')->name('shop.postRegister');
Route::get('/dang-nhap','ShopController@Login')->name('shop.Login');
Route::post('dang-nhap','ShopController@postLogin')->name('shop.postLogin');

Route::get('/admin/logout', 'ShopController@logout')->name('admin.logout');

// //trang danh sách giỏ hàng
Route::get('/danhsachgiohang','CartController@index')->name('cart.index');

//thêm sản phẩm vào giỏ hàng
Route::get('/giohang/{id}','CartController@addtoCart')->name('cart.addcart');

Route::get('Delete-cart/{id}','CartController@DeleteCart')->name('delete.cart');

Route::get('cap-nhap-so-luong-sp','CartController@updateCart')->name('update.cart');
Route::get('huy-don-hang','CartController@destroy')->name('destroy.cart');

Route::get('order-product','ShopController@OrderProduct')->name('order.product');







Route::get('/admin', 'AdminController@login')->name('admin.index');
Route::get('/admin/login', 'AdminController@login')->name('admin.login');
Route::post('/admin/login', 'AdminController@postLogin')->name('admin.postLogin');






Route::group(['prefix' => 'admin','as'=>'admin.'], function(){
    Route::post('/store','LoginController@store');
    Route::resource('photo', 'PhotoController');
    Route::resource('vendor', 'VendorController');
    Route::resource('category', 'CategoryController');
    Route::resource('user','UserController');
    Route::resource('banner','BannerController');
    Route::resource('product','ProductController');
    Route::resource('article','ArticlesController');
    Route::resource('setting', 'settingController');
    Route::resource('contact', 'ContactController');
});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;


class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = User::all();
        $users = User::latest()->paginate(10);
        
        return view('backend.user.index',['data' => $users]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.user.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // $request ->validate(
        //     [
        //         'name' => 'required|max: 255',
        //         'email' => 'required|email',
        //         'role_id' => 'required|integer',
        //         'password' => 'required|min:6',
        //         'avatar' =>'image|mines:jpeg,png,gif,svg|max: 10000'
        //     ],[
        //         'name.required' => 'bạn cần nhập họ tên',
        //         'email.email' => 'Email không được định dạng đúng',
        //         'role_id.integer' => 'nhập số nguyên',
        //         'password.min' =>'mật khẩu phải có 6 ký tự',
        //         'avatar.image'=>'file ảnh có dạng jpeg,png',
        //     ]);



        $name  = $request->input('name');
        $role_id  = (int) $request->input('role_id');
        $email = $request->input('email');
        $pwd = $request->input('password');

        $path_avatar = '';
        if ($request->hasFile('avatar')) {
            // get file
            $file = $request->file('avatar');
            // get ten
            $filename = $file->getClientOriginalName(); // lấy tên gốc của ảnh
            // duong dan upload
            $path_upload = 'upload/user/';
            // upload file
            $file->move($path_upload,$filename);
            $path_avatar = $path_upload.$filename;
        }

        $is_active = 0; // default
        if ($request->has('is_active')) {
            $is_active =(int) $request->input('is_active');
        }

        $user = new User(); // đ/n 1 đối tượng mới cụ thể từ 1 lớp.
        $user->name = $name;
        $user->role_id = $role_id;
        $user->email = $email;
        $user->password = bcrypt($pwd);
        $user->is_active = $is_active;
        $user->avatar = $path_avatar;
        $user->save();
         

        // chuyen dieu huong trang
        return redirect()->route('admin.user.index');

    }


   


    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
         //$user = User::findOrFail($id); // Tìm kiếm nhưng mà không thấy thì trả về message lỗi
        $user = User::find($id);

        return view('backend.user.edit', [
            'data' => $user
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
         // Kiểm tính đúng đắn của dữ liệu
         $request->validate([
            'role_id' => 'required|integer',
            'name' => 'required|max:255',
            'email' => 'required|email'
            //'password' => 'required|min:6',
            //'avatar' => 'image|mimes:jpeg,png,jpg,gif,svg|max:10000'
        ]);

        $name  = $request->input('name');
        $role_id  = (int) $request->input('role_id');
        $email = $request->input('email');
        $pwd = $request->input('password');



        $is_active = 0; // default
        if ($request->has('is_active')) {
            $is_active = (int) $request->input('is_active');
        }

        $user = User::find($id); // đ/n 1 đối tượng mới cụ thể từ 1 lớp.
        $user->name = $name;
        $user->role_id = $role_id;
        $user->email = $email;
        if (!empty($pwd)) {
            $user->password = bcrypt($pwd);
        }
        $user->is_active = $is_active;

        if ($request->hasFile('avatar')) {
            // get file
            $file = $request->file('avatar');
            // get ten
            $filename = $file->getClientOriginalName(); // lấy tên gốc của ảnh
            // duong dan upload
            $path_upload = 'upload/user/';
            // upload file
            $file->move($path_upload,$filename);
            $path_avatar = $path_upload.$filename;
            $user->avatar = $path_avatar;
        }

        $user->save();

        // chuyen dieu huong trang
        return redirect()->route('backend.user.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        // gọi tới hàm destroy của laravel để xóa 1 object
        // DELETE FROM ten_bang WHERE id = 33 -> execute command
        $isDelete = User::destroy($id);

        if ($isDelete) { // xóa thành công
            return response()->json(['isSuccess' => 1,'message'=>'Thành công']);
        } else {
            return response()->json(['isSuccess' => 0, 'message'=>'Thất bại']);
        }

        // Trả về dữ liệu json và trạng thái kèm theo thành công là 200
        // return response()->json(['isSuccess' => $isSuccess], $statusCode);
    }
    
}

resources/views/backend/user/create.blade.php
@extends('backend.layout.main')

@section('content')
    <section class="content-header">
        <h1>
           Quản lý User <a href="{{route('admin.user.create')}}" class="btn btn-primary"> Thêm </a>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="#">Forms</a></li>
            <li class="active">General Elements</li>
        </ol>
    </section>
    <section class="content">
      <div class="row">
        <!-- left column -->
        <div class="col-md-12">
          <!-- general form elements -->
          <div class="box box-primary">
            <div class="box-header with-border">
              <h3 class="box-title"> Thêm Thông Tin User </h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            <form role="form" action="{{Route('admin.user.store')}}" method="post" enctype="multipart/form-data">
              @csrf 
              <div class="box-body"> 

              <div class="col-md-6">
              <div class="form-group" name="role_id" id ="role_id"> 
                            <label> Chọn Quyền</label>
                            <select class="form-control">
                              <option>ADMIN</option>
                              <option>MANAGER</option>
                              <option>MEMBER</option>
                              
                            </select>
                          </div>
                
                <div class="form-group">
                    <label for="exampleInputEmail1">Họ Tên</label>
                    <input  type="Text" class="form-control" id="name" name="name" placeholder="Enter Phone">
                    @if($errors->has('name'))
                        <label class="Text-red" style="font-size:15px;font-weight:600;margin-top:5px" >
                              <i class="fa fa-info"></i>{{$errors->first('name')}}
                        </label>
                    @endif
                </div>
                <div class="form-group">
                    <label for="exampleInputEmail1">Email</label>
                    <input  type="email" class="form-control" id="email" name="email" placeholder="Enter email">
                    @if($errors->has('email'))
                        <label class="Text-red" style="font-size:15px;font-weight:600;margin-top:5px" >
                              <i class="fa fa-info"></i>{{$errors->first('email')}}
                        </label>
                    @endif
                </div>
                
                <div class="form-group">
                    <label for="exampleInputEmail1">Password</label>
                    <input  type="password" class="form-control" id="password" name="password" placeholder="Enter Phone">
                    @if($errors->has('password'))
                        <label class="Text-red" style="font-size:15px;font-weight:600;margin-top:5px" >
                              <i class="fa fa-info"></i>{{$errors->first('password')}}
                        </label>
                    @endif
                </div>

                
                <div class="form-group">
                    <label for="exampleInputFile">Avatar</label>
                    <input type="file" id="avatar" name="avatar" >

                  <p class="help-block">Example block-level help text here.</p>
                </div>
                <div class="checkbox">
                    <label>
                        <input type="checkbox" value="1" name="is_active"> Check me out
                  </label>
                </div>
                <div class="box-footer">
                <button type="submit" class="btn btn-primary">Submit</button>
              </div>
              </div>

       
              </div>
         
            </form>
          </div>
        
        </div>
        
    </section>
@endsection

resources/views/backend/user/edit.blade.php
@extends('backend.layout.main')

@section('content')
    <section class="content-header">
        <h1>
            Sửa người dùng <a href="{{route('admin.user.index')}}" class="btn bg-purple"><i class="fa fa-list"></i> Danh Sách</a>
        </h1>
    </section>

    <section class="content">
        <div class="row">
            <!-- left column -->
            <div class="col-md-6">
                <!-- general form elements -->

                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Thông tin người dùng</h3>
                    </div>
                    <!-- /.box-header -->
                    <!-- form start -->
                    <form role="form" action="{{route('admin.user.update', ['id' => $data->id ])}}" method="post" enctype="multipart/form-data">
                        @csrf
                        @method('PUT')
                        <div class="box-body">
                            <div class="form-group">
                                <label>Chọn Quyền</label>
                                <select class="form-control" name="role_id">
                                    <option value="" >-- chọn --</option>
                                    <option value="1" {{ ($data->role_id == 1) ? 'selected' : '' }} >Admin</option>
                                    <option value="2" {{ ($data->role_id == 2) ? 'selected' : '' }}>Manager</option>
                                    <option value="3" {{ ($data->role_id == 3) ? 'selected' : '' }}>Member</option>
                                </select>
                                @if ($errors->has('role_id'))
                                    <label class="text-red" style="font-weight: 600; font-size: 15px; margin-top: 5px">&ensp;<i class="fa fa-info"></i>
                                        {{ $errors->first('role_id') }}
                                    </label>
                                @endif
                            </div>
                            <div class="form-group">
                                <label for="exampleInputEmail1">Họ Tên</label>
                                <input value="{{ $data->name }}" type="text" class="form-control" id="name" name="name" placeholder="Nhập họ & tên">
                                @if ($errors->has('name'))
                                    <label class="text-red" style="font-weight: 600; font-size: 15px; margin-top: 5px">&ensp;<i class="fa fa-info"></i>
                                        {{ $errors->first('name') }}</label>
                                @endif
                            </div>
                            <div class="form-group">
                                <label for="exampleInputEmail1">Email</label>
                                <input value="{{ $data->email }}" type="text" class="form-control" id="email" name="email" placeholder="Nhập Email">
                                @if ($errors->has('email'))
                                    <label class="text-red" style="font-weight: 600; font-size: 15px; margin-top: 5px">&ensp;<i class="fa fa-info"></i> {{ $errors->first('email') }}</label>
                                @endif
                            </div>
                            <div class="form-group">
                                <label for="exampleInputEmail1" style="color: red">** Mật khẩu Mới</label>
                                <input type="password" class="form-control" id="password" name="password" placeholder="Nhập password">
                            </div>
                            <div class="form-group">
                                <label for="exampleInputFile">New Avatar</label>
                                <input type="file" id="avatar" name="avatar">
                                <img src="{{ asset($data->avatar) }}" alt="" width="100" style="margin-top: 10px;">
                            </div>
                            <div class="checkbox">
                                <label>
                                    <input {{ ($data->is_active == 1) ? 'checked' : '' }} type="checkbox" value="1" name="is_active"> Kích hoạt tài khoản
                                </label>
                            </div>
                        </div>
                        <!-- /.box-body -->

                        <div class="box-footer">
                            <button type="submit" class="btn btn-primary">Lưu</button>
                        </div>
                    </form>
                </div>
                <!-- /.box -->
            </div>
            
        </div>
        <!-- /.row -->
    </section>
@endsection

resources/views/backend/user/index.blade.php
@extends('backend.layout.main')

@section('content')
    <section class="content-header">
        <h1>
            QL User <a href="{{ route('admin.user.create') }}" class="btn bg-purple btn-flat"><i class="fa fa-plus"></i> Thêm</a>
        </h1>
        <ol class="breadcrumb">
            <li><a href="/"><i class="fa fa-dashboard"></i> Trang chủ</a></li>
            <li class="active">QL Danh Sách - Nhà Cung Cấp</li>
        </ol>
    </section>

    <section class="content">
        <div class="row">
            <div class="col-md-12">
                <div class="box">
                    <div class="box-header with-border">
                        <h3 class="box-title">Danh Sách Người Dùng</h3>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <table class="table table-bordered">
                            <tbody>
                            <tr>
                                <th style="width: 10px">STT</th>
                                <th>Avatar</th>
                                <th>Tên</th>
                                <th>Email</th>
                                <th>Ngày Cấp</th>
                                <th>Trạng Thái</th>
                                <th>Hành Động</th>
                            </tr>

                            @foreach($data as $key => $item)
                                <tr class="item-{{ $item->id }}">
                                    <td>{{ $key +1 }}</td>
                                    <td><img src="{{ asset($item->avatar) }}" width="70" /></td>
                                    <td>{{ $item->name }}</td>
                                    <td>{{ $item->email }}</td>
                                    <td>{{ $item->created_at }}</td>
                                    <td>{{ $item->is_active == 1 ? 'Show' : 'Hide' }}</td>
                                    <td class="text-center">
                                        <a href="{{ route('admin.user.edit', ['id' => $item->id ]) }}" class="btn btn-flat bg-purple"><i class="fa fa-pencil"></i></a>
                                        <button data-id="{{ $item->id }}" class="btn btn-danger btn-delete"><i class="fa fa-trash"></i></button>
                                    </td>
                                </tr>

                            @endforeach

                            </tbody>
                        </table>

                    </div>
                    <!-- /.box-body -->
                    <div class="box-footer clearfix">
                        {{ $data->links() }}
                    </div>
                </div>
                <!-- /.box -->
            </div>
            <!-- /.col -->
        </div>
    </section>
@endsection

@section('my_js')
    <script type="text/javascript">
        $(document).ready(function() {
            // Thiết lập csrf => chổng giả mạo
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN' : $('meta[name="csrf-token"]').attr('content')
                }
            })

            $('.btn-delete').on('click',function () {

                let id = $(this).data('id');

                let result = confirm("Bạn có chắc chắn muốn xóa ?");

                if (result) { // neu nhấn == ok , sẽ send request ajax

                    $.ajax({
                        url: '/admin/user/'+id, // http://webthucpham.local:8888/user/8
                        type: 'DELETE', // phương truyền tải dữ liệu
                        data: {
                            // dữ liệu truyền sang nếu có
                            name : 'dung'
                        },
                        dataType: "json", // kiểu dữ liệu muốn nhận về
                        success: function (res) {
                            //  PHP : $user->name
                            //  JS: res.name

                            if (res.success != 'undefined' && res.success == 1) { // xóa thành công
                                $('.item-'+id).remove();
                            }
                            window.location.href = '/admin/user';
                        },
                        error: function (e) { // lỗi nếu có
                            console.log(e);
                        }
                    });
                }

            });

            /*$( ".btn-delete" ).click(function() {
                alert( "Handler for .click() called." );
            });*/

        });
    </script>
@endsection